---
- name: Run Python and view the generated log
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run python
      ansible.builtin.shell: python test.py
    - name: Check log
      ansible.builtin.shell: cat test.log
      register: result
    - name: "View Result"
      debug: var=result.stdout_lines
