all:
  children:
    euro_group:
      hosts:
        vIOS-197:
          ansible_connection: network_cli
          ansible_host: 192.168.1.197
          ansible_network_os: cisco.ios.ios
          ansible_ssh_pass: europass
          ansible_ssh_user: euro
        vIOS-199:
          ansible_connection: network_cli
          ansible_host: 192.168.1.199
          ansible_network_os: cisco.ios.ios
          ansible_ssh_pass: europass
          ansible_ssh_user: euro
    ungrouped:
      hosts:
        vIOS-196:
          ansible_connection: network_cli
          ansible_host: 192.168.1.196
          ansible_network_os: cisco.ios.ios
          ansible_ssh_pass: demo
          ansible_ssh_user: john
          loopback201_ip: 201.201.201.201
        vIOS-201:
          ansible_connection: network_cli
          ansible_host: 192.168.1.201
          ansible_network_os: cisco.ios.ios
          ansible_ssh_pass: demo
          ansible_ssh_user: john
          loopback201_ip: 201.201.201.201
    usa_group:
      hosts:
        vIOS-198:
          ansible_connection: network_cli
          ansible_host: 192.168.1.198
          ansible_network_os: cisco.ios.ios
          ansible_ssh_pass: usapass
          ansible_ssh_user: usa
        vIOS-200:
          ansible_connection: network_cli
          ansible_host: 192.168.1.200
          ansible_network_os: cisco.ios.ios
          ansible_ssh_pass: usapass
          ansible_ssh_user: usa
