---
- name: Run Python and view the generated log
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run python
      ansible.builtin.shell: python ../test.py
    - name: Check log
      ansible.builtin.shell: cat /home/swils024/Documents/ansible/roles/common/logs/test.log
      register: result
    - name: "View Result"
      debug: var=result.stdout_lines
