---
- name: First Playbook
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Create Loopback10 with description"
      ios_config:
        lines:
           - description Configured by ansible
        parents:
           - interface Loopback10
